const room=document.querySelector('#room'),desc=document.querySelector('#desc'),primary=document.querySelector('#primary'),photo=document.querySelector('.photo');
let dim=false,ctx,gain,tvCtx,tvGain,moving=false,dragStart=0,dragging=false;
const state={bed:{covered:false,sleepy:false},sofa:{covered:false},window:{open:false},table:{warm:false}};
const data={bed:['창밖을 바라보며, 천천히 쉬어가요.','이불 더 덮기'],window:['유리 위로 흐르는 빗방울을 가까이 바라봅니다.','창문 조금 열기'],sofa:['담요를 덮고 조용한 화면과 빗소리를 즐깁니다.','담요 덮기'],table:['따뜻한 차에서 올라오는 김을 바라봅니다.','따뜻한 차 마시기']};
const AudioCtx=window.AudioContext||window.webkitAudioContext;
function labelFor(s){if(s==='bed')return state.bed.covered?'이불 살짝 내리기':data.bed[1];if(s==='sofa')return state.sofa.covered?'담요 살짝 내리기':data.sofa[1];if(s==='window')return state.window.open?'창문 닫기':data.window[1];return data.table[1]}
function syncScene(){const s=room.dataset.scene;primary.textContent=labelFor(s);room.classList.toggle('covered',!!state[s]?.covered);room.classList.toggle('sleepy',s==='bed'&&state.bed.sleepy);room.classList.toggle('window-open',s==='window'&&state.window.open);room.classList.toggle('tea-warm',s==='table'&&state.table.warm)}
function go(s){if(moving||!data[s]||s===room.dataset.scene)return;moving=true;room.classList.add('moving');navigator.vibrate?.(8);photo.style.marginLeft='0px';setTimeout(()=>{room.dataset.scene=s;document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===s));desc.textContent=data[s][0];syncScene()},300);setTimeout(()=>{room.classList.remove('moving');moving=false},700)}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('[data-hotspot]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(!dragging)go(b.dataset.hotspot)});
primary.onclick=()=>{const s=room.dataset.scene;if(s==='bed'){state.bed.covered=!state.bed.covered;state.bed.sleepy=state.bed.covered}else if(s==='sofa'){state.sofa.covered=!state.sofa.covered}else if(s==='window'){state.window.open=!state.window.open;if(gain)gain.gain.value=state.window.open?.13:.055}else{state.table.warm=true;clearTimeout(state.table.timer);state.table.timer=setTimeout(()=>{state.table.warm=false;syncScene()},9000)}syncScene()};
document.querySelector('#light').onclick=()=>{dim=!dim;room.classList.toggle('dim',dim);document.querySelector('#light').textContent=dim?'조명 밝히기':'조명 낮추기'};
document.querySelector('#sound').onclick=async e=>{const btn=e.currentTarget;if(!AudioCtx)return btn.textContent='소리 미지원';if(!ctx){ctx=new AudioCtx();const n=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=n.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.18;const src=ctx.createBufferSource(),f=ctx.createBiquadFilter();src.buffer=n;src.loop=true;f.type='lowpass';f.frequency.value=1250;gain=ctx.createGain();gain.gain.value=state.window.open?.13:.055;src.connect(f).connect(gain).connect(ctx.destination);src.start()}if(ctx.state==='suspended')await ctx.resume();const on=gain.gain.value>0;if(btn.dataset.started){gain.gain.value=on?0:(state.window.open?.13:.055)}else btn.dataset.started='1';btn.textContent=gain.gain.value?'빗소리 끄기':'빗소리 켜기'};
document.querySelector('#play').onclick=e=>{const btn=e.currentTarget;btn.textContent=btn.textContent==='Ⅱ'?'▶':'Ⅱ'};
document.querySelector('#tvSound').onclick=async e=>{const btn=e.currentTarget;if(!AudioCtx)return btn.textContent='소리 미지원';if(!tvCtx){tvCtx=new AudioCtx();const o=tvCtx.createOscillator(),g=tvCtx.createGain();o.type='triangle';o.frequency.value=185;g.gain.value=.012;o.connect(g).connect(tvCtx.destination);o.start();tvGain=g}else tvGain.gain.value=tvGain.gain.value?0:.012;if(tvCtx.state==='suspended')await tvCtx.resume();btn.textContent=tvGain.gain.value?'TV 소리 끄기':'TV 소리'};
room.addEventListener('pointerdown',e=>{dragStart=e.clientX;dragging=false});
room.addEventListener('pointermove',e=>{if(!e.buttons)return;const delta=e.clientX-dragStart;if(Math.abs(delta)>8)dragging=true;const dx=Math.max(-12,Math.min(12,delta/35));photo.style.marginLeft=dx+'px'});
room.addEventListener('pointerup',()=>{setTimeout(()=>dragging=false,0);photo.style.marginLeft='0px';reveal()});
let idle;function reveal(){room.classList.add('showspots');clearTimeout(idle);idle=setTimeout(()=>room.classList.remove('showspots'),1700)}
let uiTimer;function wakeUI(){if(room.classList.contains('resting'))return;room.classList.remove('ui-hidden');clearTimeout(uiTimer);uiTimer=setTimeout(()=>room.classList.add('ui-hidden'),5200)}['pointerdown','pointermove','touchstart'].forEach(ev=>room.addEventListener(ev,wakeUI,{passive:true}));wakeUI();
const zen=document.querySelector('#zen');zen.onclick=e=>{e.stopPropagation();const on=room.classList.toggle('resting');room.classList.remove('ui-hidden');zen.textContent=on?'돌아오기':'휴식 모드';if(on&&gain&&gain.gain.value)gain.gain.value=.07;else wakeUI()};
document.addEventListener('visibilitychange',async()=>{for(const a of [ctx,tvCtx])if(a){if(document.hidden)await a.suspend();else await a.resume()}});
const clock=document.querySelector('#clock'),caption=document.querySelector('#caption');function tick(){const d=new Date();clock.textContent=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}tick();setInterval(tick,30000);
function say(t){caption.textContent=t;caption.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>caption.classList.remove('show'),2600)}
document.querySelectorAll('[data-go],[data-hotspot]').forEach(b=>b.addEventListener('click',()=>{const s=b.dataset.go||b.dataset.hotspot;if(data[s])setTimeout(()=>say({bed:'이불 속으로 돌아왔어요.',window:'빗소리가 조금 더 가까워졌어요.',sofa:'TV 불빛이 방 안에 번져요.',table:'따뜻한 차 한 잔을 준비했어요.'}[s]),720)}));
primary.addEventListener('click',()=>{const s=room.dataset.scene;if(s==='table')say('머그컵에서 따뜻한 김이 올라와요.');if(s==='window')say(state.window.open?'차가운 바람과 빗소리가 들어와요.':'다시 방 안이 조용해졌어요.');if(s==='bed')say(state.bed.sleepy?'조금 더 깊이 이불 속으로.':'다시 눈을 떠요.');if(s==='sofa')say(state.sofa.covered?'담요와 TV 불빛이 조금 더 따뜻해요.':'담요를 살짝 내려놓았어요.')});
syncScene();